@echo off
rem Local-only backend defaults for ProjTrack development.
rem This file intentionally sets non-production values so copied production .env examples
rem do not make local startup fail or try to use real providers.
set "NODE_ENV=development"
set "APP_ENV=development"
set "PORT=3001"
set "DATABASE_URL=postgresql://projtrack:projtrack@127.0.0.1:5432/projtrack?schema=public"
set "APP_URL=http://127.0.0.1:5173"
set "CORS_ORIGINS=http://localhost:5173,http://127.0.0.1:5173"
set "JWT_ACCESS_SECRET=local-dev-access-secret-change-before-production-1234567890"
set "JWT_REFRESH_SECRET=local-dev-refresh-secret-change-before-production-1234567890"
set "MAIL_PROVIDER=stub"
set "MAIL_WORKER_ENABLED=false"
set "TESTMAIL_ENABLED=false"
set "MAIL_FROM_NAME=ProjTrack"
set "MAIL_FROM_ADMIN=admin@projtrack.codes"
set "MAIL_FROM_NOREPLY=support@projtrack.codes"
set "MAIL_FROM_INVITE=support@projtrack.codes"
set "MAIL_FROM_NOTIFY=notification@projtrack.codes"
set "MAIL_FROM_SUPPORT=support@projtrack.codes"
set "OBJECT_STORAGE_MODE=local"
set "FILE_STORAGE_MODE=local"
set "S3_BUCKET="
set "S3_REGION="
set "S3_ENDPOINT="
set "S3_ACCESS_KEY_ID="
set "S3_SECRET_ACCESS_KEY="
set "BACKUP_WORKER_ENABLED=false"
set "BACKUP_LOCAL_DIR=data/system-tools/backups"
set "ALLOW_DEMO_SEED=true"
set "ALLOW_SEED_DATA_CLEANUP=false"
set "ALLOW_PRODUCTION_ADMIN_TOOL_RUNS=false"
